import type { Metadata } from "next";
// import { Noto_Serif_Bengali } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/Navbar";
import Marquee from "./Components/Marquee";

import { Noto_Sans_Bengali } from "next/font/google";

const notoSansBengali = Noto_Sans_Bengali({
  variable: "--font-noto-sans-bengali",
  subsets: ["latin", "bengali"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="bn" data-theme="light"
      className={`${notoSansBengali.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">

        <Navbar/>
        <Marquee/>
        {children}
      </body>
    </html>
  );
}